name:  'Get & cache dependencies'
description: 'get the Dependencied and cache them'
runs:
  using: 'composite'
  steps:
    - name: cache Dependency
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci 
      shell: bash
