name: second work flow
on:
    push:
        branches:
          - master
jobs:
    
    call-reusable:
        uses: ./.github/workflows/reusable.yml
        with:
            testVar: 20



           
